### ISSUE TITLE
拓展到病理阅片的可能性探讨

### ISSUE THREAD

**Issue by Yeanous** [WangRongsheng/XrayGLM#1]
病理切片以及脱落细胞形态学也是同样静态的具有显著特征的图片。现有的自动阅片系统，事实上已经具备了一定的判读功能。应用相似的训练方法应该也能生成可供临床参考的报告。

**Comment by WangRongsheng** [comment]
是的，具有`图像-文本`对的数据大概率上都是能完成这样一个过程的。
