### ISSUE TITLE
模型微调出错 

### ISSUE THREAD

**Issue by 2132660698** [WangRongsheng/XrayGLM#10]
![image](https://github.com/WangRongsheng/XrayGLM/assets/94035926/c282c484-7c60-4b95-9a0d-bf6fc25644e7)

AttributeError 'FakeTokenizer' object has no attribute 'pad_token_id'
AttributeError 'FakeTokenizer' object has no attribute 'encode'

**Comment by 2132660698** [comment]
还有/data/Xray/openi-zh.json里面的数据格式和代码不匹配，能否提供一份匹配的文件，谢谢。

**Comment by WangRongsheng** [comment]
我想您的finetune_XrayGLM.py文件或许跟XrayGLM下的不太一样：

https://github.com/WangRongsheng/XrayGLM/blob/main/finetune_XrayGLM.py#L115
```python
input0 = tokenizer.encode("<img>", add_special_tokens=False)
```

XrayGLM的仓库中上述代码在第115行，但是您的报错中显示在122行。这或许有一些其它的代码被添加，请检查

**Comment by 2132660698** [comment]
把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把args.tokenizer_type='THUDM/chatglm-6b'替换成本地的路径就可以了

这个配置成本地后，问题解决了，非常感谢大家。

**Comment by higher127** [comment]
> 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把args.tokenizer_type='THUDM/chatglm-6b'替换成本地的路径就可以了
> 
> 这个配置成本地后，问题解决了，非常感谢大家。

能给个示例吗？1.[相关代码](https://huggingface.co/THUDM/chatglm-6b)是指什么，放到本地哪？2.args.tokenizer_type='THUDM/chatglm-6b'替换成本地的路径，比如我的本地路径是“/root/.sat_model/visualglm-6b/1/mp_rank_00_model_states.pt”，我就直接改成args.tokenizer_type='/root/.sat_model/visualglm-6b/1/mp_rank_00_model_states.pt' ？

**Comment by higher127** [comment]
> > 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把args.tokenizer_type='THUDM/chatglm-6b'替换成本地的路径就可以了
> > 这个配置成本地后，问题解决了，非常感谢大家。
> 
> 能给个示例吗？1.[相关代码](https://huggingface.co/THUDM/chatglm-6b)是指什么，放到本地哪？2.args.tokenizer_type='THUDM/chatglm-6b'替换成本地的路径，比如我的本地路径是“/root/.sat_model/visualglm-6b/1/mp_rank_00_model_states.pt”，我就直接改成args.tokenizer_type='/root/.sat_model/visualglm-6b/1/mp_rank_00_model_states.pt' ？

回答：1.将https://huggingface.co/THUDM/chatglm-6b全部下载到本地，如“/root/chatglm-6b”；2.args.tokenizer_type='/root/chatglm-6b'即可。
