### ISSUE TITLE
无法正常微调

### ISSUE THREAD

**Issue by menkeyi** [WangRongsheng/XrayGLM#12]
finetune_XrayGLM.py
image = processor(Image.open(item['img']).convert('RGB'))  图像路径不对

item['prompt']  和  item['label']  跟openi-zh.json对应不上
[诊疗报告(中文)](https://github.com/WangRongsheng/XrayGLM/blob/main/data/Xray/openi-zh.json)

class FewShotDataset(Dataset):
    def __init__(self, path, processor, tokenizer, args):
        max_seq_length = args.max_source_length + args.max_target_length
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        self.images = []
        self.input_ids = []
        self.labels = []
        for item in data:
            image = processor(Image.open(item['img']).convert('RGB'))
            input0 = tokenizer.encode("<img>", add_special_tokens=False)
            input1 = [tokenizer.pad_token_id] * args.image_length
            input2 = tokenizer.encode("</img>问："+item['prompt']+"\n答：", add_special_tokens=False)
            a_ids = sum([input0, input1, input2], [])
            b_ids = tokenizer.encode(text=item['label'], add_special_tokens=False)
            if len(a_ids) > args.max_source_length - 1:
                a_ids = a_ids[: args.max_source_length - 1]
            if len(b_ids) > args.max_target_length - 2:
                b_ids = b_ids[: args.max_target_length - 2]
            pre_image = len(input0)
            input_ids = tokenizer.build_inputs_with_special_tokens(a_ids, b_ids)

            context_length = input_ids.index(tokenizer.bos_token_id)
            mask_position = context_length - 1
            labels = [-100] * context_length + input_ids[mask_position+1:]
            
            pad_len = max_seq_length - len(input_ids)
            input_ids = input_ids + [tokenizer.pad_token_id] * pad_len
            labels = labels + [tokenizer.pad_token_id] * pad_len

**Comment by WangRongsheng** [comment]
或许您可以检查一下这个路径https://github.com/WangRongsheng/XrayGLM/blob/main/finetune_XrayGLM.sh#L20

**Comment by anothersin** [comment]
> 或许您可以检查一下这个路径https://github.com/WangRongsheng/XrayGLM/blob/main/finetune_XrayGLM.sh#L20

请检查你的openi-zh.json或者修改FewShotDataset。FewShotDataset里面的key与json文件里面不同，比如类里面的是img，prompt和 label 然而json里面是image_id与caption。并且在data = json.load(f)之后还需要通过annotations来查询到前面所描述的信息。

**Comment by lvboodvl** [comment]
@menkeyi 您好，我也遇到类似的问题，后来看了下openi-zh.json的字典结构和key，自己修改了一个数据读取方式如下：
class FewShotDataset(Dataset):
    def __init__(self, path, processor, tokenizer, args):
        max_seq_length = args.max_source_length + args.max_target_length
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        self.images = []
        self.input_ids = []
        self.labels = []
        for item in data["annotations"]:
            image = processor(Image.open('./data/Xray/' + item['image_id'] + '.png').convert('RGB'))
            input0 = tokenizer.encode("<img>", add_special_tokens=False)
            input1 = [tokenizer.pad_token_id] * args.image_length
            input2 = tokenizer.encode("</img>问："+"请诊断一下这张x光片"+"\n答：", add_special_tokens=False)
            a_ids = sum([input0, input1, input2], [])
            b_ids = tokenizer.encode(text=item['caption'], add_special_tokens=False)
            if len(a_ids) > args.max_source_length - 1:
                a_ids = a_ids[: args.max_source_length - 1]
            if len(b_ids) > args.max_target_length - 2:
                b_ids = b_ids[: args.max_target_length - 2]
            pre_image = len(input0)
            input_ids = tokenizer.build_inputs_with_special_tokens(a_ids, b_ids)

            context_length = input_ids.index(tokenizer.bos_token_id)
            mask_position = context_length - 1
            labels = [-100] * context_length + input_ids[mask_position+1:]
            
            pad_len = max_seq_length - len(input_ids)
            input_ids = input_ids + [tokenizer.pad_token_id] * pad_len
            labels = labels + [tokenizer.pad_token_id] * pad_len
            if args.ignore_pad_token_for_loss:
                labels = [(l if l != tokenizer.pad_token_id else -100) for l in labels]
            self.images.append(image)
            self.input_ids.append(input_ids)
            self.labels.append(labels)
        self.pre_image = pre_image

**Comment by menkeyi** [comment]
> caption

谢谢可以正常跑了

**Comment by anothersin** [comment]
> 

不是像他这样的，我看了一下data下面的几个py文件，需要生成类似于https://github.com/WangRongsheng/XrayGLM/blob/main/data/openi-ch-random.json 这样的json，你可以看看data下面的build*.py

**Comment by lvboodvl** [comment]
对的，应该运行build_ch_prompt.py把openi-zh.json转成openi-zh-prompt.json，再在finetune_XrayGLM.sh的第20，21行把路径更新成./data/Xray/openi-zh-prompt.json 就可以了

**Comment by anothersin** [comment]
> 对的，应该运行build_ch_prompt.py把openi-zh.json转成openi-zh-prompt.json，再在finetune_XrayGLM.sh的第20，21行把路径更新成./data/Xray/openi-zh-prompt.json 就可以了

您好，请问在fintune.sh上的train-iters 300是正确的嘛，很快训练就结束了
