### ISSUE TITLE
在COLAB上运行出现错误

### ISSUE THREAD

**Issue by xiaoli26** [WangRongsheng/XrayGLM#13]
运行的时候输入URL和图片地址均无法继续，也无法切换成纯文本模式

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/lib64-nvidia did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//172.28.0.1'), PosixPath('8013'), PosixPath('http')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https'), PosixPath('//colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-a100-s-1ar02uode6jjs --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('module'), PosixPath('//ipykernel.pylab.backend_inline')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
[2023-05-31 02:32:05,739] [INFO] building FineTuneVisualGLMModel model ...
41239
[2023-05-31 02:32:05,741] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-05-31 02:32:05,742] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
/usr/local/lib/python3.10/dist-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
replacing layer 0 with lora
replacing layer 14 with lora
[2023-05-31 02:32:19,816] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 7811237376
[2023-05-31 02:32:20,765] [INFO] [RANK 0] global rank 0 is loading checkpoint checkpoints/300/mp_rank_00_model_states.pt
[2023-05-31 02:32:30,374] [INFO] [RANK 0] > successfully loaded checkpoints/300/mp_rank_00_model_states.pt
[2023-05-31 02:32:30,995] [INFO] [RANK 0] > Quantizing model weight to 8 bits
[2023-05-31 02:32:43,283] [INFO] [RANK 0] > Quantized 5502926848 parameters in total.
Downloading (…)okenizer_config.json: 100% 441/441 [00:00<00:00, 2.18MB/s]
Downloading (…)enization_chatglm.py: 100% 17.0k/17.0k [00:00<00:00, 48.8MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm-6b:
- tokenization_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading ice_text.model: 100% 2.71M/2.71M [00:00<00:00, 35.7MB/s]
欢迎使用 XrayGLM 模型，输入图像URL或本地路径读图，继续输入内容对话，clear 重新开始，stop 终止程序
请输入图像路径或URL（回车进入纯文本对话）： 
用户：
"addmm_impl_cpu_" not implemented for 'Half'
请输入图像路径或URL（回车进入纯文本对话）： https://img2.baidu.com/it/u=3401817238,2820605663&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=375
"slow_conv2d_cpu" not implemented for 'Half'
请输入图像路径或URL（回车进入纯文本对话）： /content/XrayGLM/2577_1.png
cannot identify image file '/content/XrayGLM/2577_1.png'
请输入图像路径或URL（回车进入纯文本对话）： /2577_1.png
[Errno 2] No such file or directory: '/2577_1.png'
请输入图像路径或URL（回车进入纯文本对话）： 2577_1.png
cannot identify image file '2577_1.png'

**Comment by WangRongsheng** [comment]
可能它无法正确读取到图片的路径，稍后我们会debug一下，感谢反馈

**Comment by xiaoli26** [comment]
> 可能它无法正确读取到图片的路径，稍后我们会debug一下，感谢反馈

谢谢回复

**Comment by shibing624** [comment]
> 可能它无法正确读取到图片的路径，稍后我们会debug一下，感谢反馈

+1

**Comment by shibing624** [comment]
找到问题了，示例图片有问题，用自己的图就可以了： https://i.pinimg.com/originals/00/3f/79/003f79b23296bf8de8cecb6f38d87f23.jpg
