### ISSUE TITLE
关于文本报告数据的疑问

### ISSUE THREAD

**Issue by zoule41** [WangRongsheng/XrayGLM#16]
根据OpenI官网（https://openi.nlm.nih.gov/faq#collection）提供的报告下载链接，我下载到的英文原始报告有时候不完整，部分字符以XXXX代替，然而您的项目里英文报告对应的caption部分好像都是完整的信息。
因此想请教作者是采用了什么预处理方法对报告的信息进行补全吗？
例如“CXR2_IM-0652-2001.jpg”的原始英文报告文件2.xml中相关信息如下：
<Abstract>
<AbstractText Label="COMPARISON">None.</AbstractText>
<AbstractText Label="INDICATION">Preop bariatric surgery.</AbstractText>
<AbstractText Label="FINDINGS">Borderline cardiomegaly. Midline sternotomy XXXX. Enlarged pulmonary arteries. Clear lungs. Inferior XXXX XXXX XXXX.</AbstractText>
<AbstractText Label="IMPRESSION">No acute pulmonary findings.</AbstractText>
相应的作者项目里的caption部分内容是：
"image_id": "2_1",
 "caption": "Borderline cardiomegaly with midline sternotomy scar. Enlarged pulmonary arteries with clear lungs. No acute pulmonary abnormalities noted on the X-ray examination. The heart is borderline enlarged with a midline sternotomy scar observed. The pulmonary arteries are mildly enlarged." 很好奇作者项目里的caption内容针对原始数据进行了怎样的处理。

**Comment by WangRongsheng** [comment]
将XML的信息作为上下文输入给ChatGPT让它整理生成一份报告信息（`caption`），对于一些xxx信息可以采取忽略。
