### ISSUE TITLE
微调训练时自动退出

### ISSUE THREAD

**Issue by hunwenpinghao** [WangRongsheng/XrayGLM#19]
8x v100 (16G) 是内存不够吗？我在微调训练时出现了自动退出问题，有人遇到过吗？

![image](https://github.com/WangRongsheng/XrayGLM/assets/66299193/85374a8f-8bc1-49bd-95ec-b888f184428c)
![image](https://github.com/WangRongsheng/XrayGLM/assets/66299193/3ccedee6-d3ef-4844-9b51-fef5687b5a24)
![image](https://github.com/WangRongsheng/XrayGLM/assets/66299193/4e729ce6-7bb6-407a-b61c-6d0ad83928f1)

**Comment by WangRongsheng** [comment]
16GB内存有点小哦
