### ISSUE TITLE
您好，开始微调时加载完VisualGLM-6B，提示还需要加载ChatGLM-6B参数吗？如果加载是全部权重吗？

### ISSUE THREAD

**Issue by MCenyuan** [WangRongsheng/XrayGLM#23]
/root/autodl-tmp/XrayGLM/chatglm-6b tokenizer! Now you can get tokenizer() everywhere

其中ChatGLM-6B中的tokenizer()需要全部的权重吗？

**Comment by MCenyuan** [comment]
我传了ChatGLM-6B的一个bin文件，发现代码也能运行。是不是要ChatGLM-6B的所有权重？

**Comment by freelancerllm** [comment]
> /root/autodl-tmp/XrayGLM/chatglm-6b tokenizer! Now you can get tokenizer() everywhere
> 
> 其中ChatGLM-6B中的tokenizer()需要全部的权重吗？

tokenizer加载的是词表吧

**Comment by MCenyuan** [comment]
tokenizer是词表，我想确定以下权重一共加载几次？是仅仅加载VisualGLM-6B？还是加载完VisualGLM-6B后加载ChatGLM-6B？

**Comment by Sowhat007** [comment]
测试了一下，加载VisualGLM的全部模型或者ChatGLM全部的模型，都可以正常跑起来，而且效果差不多。
    #tokenizer = AutoTokenizer.from_pretrained("/data/visualglm-6b", trust_remote_code=True)    
    #tokenizer = AutoTokenizer.from_pretrained("/data/chatglm-6b", trust_remote_code=True)
