### ISSUE TITLE
为什么我的微调效果很差

### ISSUE THREAD

**Issue by Xue-Yw** [WangRongsheng/XrayGLM#30]
1.请问为什么和作者一样微调3000次我的模型几乎不能回答问题，而且好像次数越多效果越差
2.请问作者在GitHub上展示的微调效果是只用了Openl这一个数据集训练的吗
![image](https://github.com/WangRongsheng/XrayGLM/assets/56827857/a31496fa-0d44-4d61-8a9d-86ca0f9c15bd)
![image](https://github.com/WangRongsheng/XrayGLM/assets/56827857/d55a54cc-9bde-4bc1-95c3-c5241d5cb240)

**Comment by MCenyuan** [comment]
微调多少次？

**Comment by WangRongsheng** [comment]
微调次数在500-3000比较好，过大的轮次容易导致过拟合。（3000其实也有些过拟合问题）

**Comment by Xue-Yw** [comment]
> 
但为什么您展示的微调效果那么好呢，是有别的需要做的吗

**Comment by WangRongsheng** [comment]
> 

所有我们训练的东西都已经开源并且做了说明。
