### ISSUE TITLE
FineTuneVisualGLMModel

### ISSUE THREAD

**Issue by likeboo** [WangRongsheng/XrayGLM#31]
Traceback (most recent call last):
  File "D:\AI\XrayGLM\web_demo.py", line 154, in <module>
    main(args)
  File "D:\AI\XrayGLM\web_demo.py", line 90, in main
    model, model_args = AutoModel.from_pretrained(
  File "E:\anaconda3\envs\pytorch18\lib\site-packages\sat\model\base_model.py", line 275, in from_pretrained
    model_cls = model_registry.get(args.model_class)
  File "E:\anaconda3\envs\pytorch18\lib\site-packages\sat\model\registry.py", line 17, in get
    raise ValueError(f'model_class {name} not found.')
ValueError: model_class FineTuneVisualGLMModel not found.

现有模型的配置文件不全吧。 我修改成VisualGLMModel类型后，又找不到
 File "D:\AI\XrayGLM\web_demo.py", line 90, in main
    model, model_args = AutoModel.from_pretrained(
  File "E:\anaconda3\envs\pytorch18\lib\site-packages\sat\model\base_model.py", line 284, in from_pretrained
    load_checkpoint(model, args, load_path=model_path, prefix=prefix)
  File "E:\anaconda3\envs\pytorch18\lib\site-packages\sat\training\model_io.py", line 184, in load_checkpoint
    iteration, release, success = get_checkpoint_iteration(load_path)
  File "E:\anaconda3\envs\pytorch18\lib\site-packages\sat\training\model_io.py", line 152, in get_checkpoint_iteration
    raise ValueError('could not find the metadata file {}, please check --load'.format(
ValueError: could not find the metadata file checkpoints\latest, please check --load

求解答，我是WINDOWS还没内有尝试自己微调。

**Comment by likeboo** [comment]
raise ValueError(f'Missing keys for inference: {missing_keys}.\nIf you still want to inference anyway, pass --force_inference to args.')
ValueError: Missing keys for inference: ['transformer.layers.0.attention.query_key_value.weight', 'transformer.layers.0.attention.query_key_value.bias', 'transformer.layers.0.attention.dense.weight', 'trans
former.layers.0.attention.dense.bias', 'transformer.layers.14.attention.query_key_value.weight', 'transformer.layers.14.attention.query_key_value.bias', 'transformer.layers.14.attention.dense.weight', 'transformer.layers.14.attention.dense.bias'].
If you still want to inference anyway, pass --force_inference to args.
---------------------
那个配置文件有问题，我修改了配置OK了 但是LORO好像不能加载。。

**Comment by lovelucymuch** [comment]
> ```
> raise ValueError(f'Missing keys for inference: {missing_keys}.\nIf you still want to inference anyway, pass --force_inference to args.')
> ```
> 
> ## ValueError: Missing keys for inference: ['transformer.layers.0.attention.query_key_value.weight', 'transformer.layers.0.attention.query_key_value.bias', 'transformer.layers.0.attention.dense.weight', 'trans
> former.layers.0.attention.dense.bias', 'transformer.layers.14.attention.query_key_value.weight', 'transformer.layers.14.attention.query_key_value.bias', 'transformer.layers.14.attention.dense.weight', 'transformer.layers.14.attention.dense.bias'].
> If you still want to inference anyway, pass --force_inference to args.
> 那个配置文件有问题，我修改了配置OK了 但是LORO好像不能加载。。

请问你是如何修改的latest配置文件？非常感谢！
我也报同样的错误：ValueError: could not find the metadata file checkpoints/checkpoints-XrayGLM-3000/latest, please check --load

**Comment by WillowRw** [comment]
> ```
> raise ValueError(f'Missing keys for inference: {missing_keys}.\nIf you still want to inference anyway, pass --force_inference to args.')
> ```
> 
> ## ValueError: Missing keys for inference: ['transformer.layers.0.attention.query_key_value.weight', 'transformer.layers.0.attention.query_key_value.bias', 'transformer.layers.0.attention.dense.weight', 'trans
> former.layers.0.attention.dense.bias', 'transformer.layers.14.attention.query_key_value.weight', 'transformer.layers.14.attention.query_key_value.bias', 'transformer.layers.14.attention.dense.weight', 'transformer.layers.14.attention.dense.bias'].
> If you still want to inference anyway, pass --force_inference to args.
> 那个配置文件有问题，我修改了配置OK了 但是LORO好像不能加载。。

是怎样修改的呀~

**Comment by WillowRw** [comment]
from finetune_XrayGLM import FineTuneVisualGLMModel
model, args = FineTuneVisualGLMModel.from_pretrained('path', args=argparse.Namespace( fp16=True, skip_init=True, use_gpu_initialization=True, device='cuda', ))改成这个就行了

**Comment by TwinkleYR** [comment]
> > ```
> > raise ValueError(f'Missing keys for inference: {missing_keys}.\nIf you still want to inference anyway, pass --force_inference to args.')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## ValueError: Missing keys for inference: ['transformer.layers.0.attention.query_key_value.weight', 'transformer.layers.0.attention.query_key_value.bias', 'transformer.layers.0.attention.dense.weight', 'trans
> > former.layers.0.attention.dense.bias', 'transformer.layers.14.attention.query_key_value.weight', 'transformer.layers.14.attention.query_key_value.bias', 'transformer.layers.14.attention.dense.weight', 'transformer.layers.14.attention.dense.bias'].
> > If you still want to inference anyway, pass --force_inference to args.
> > 那个配置文件有问题，我修改了配置OK了 但是LORO好像不能加载。。
> 
> 是怎样修改的呀~

我也出现了同样的错误，没有修改配置文件，重新下载模型后解决了此问题，模型下载地址如下所示：https://blog.csdn.net/weixin_42179685/article/details/135499185
