### ISSUE TITLE
cli_demo: cannot identify image file

### ISSUE THREAD

**Issue by AriesChen-UPC** [WangRongsheng/XrayGLM#33]
Test using Google Colab A100. 
When using the "cli_demo", the following image reading problem occurred.
```
请输入图像路径或URL（回车进入纯文本对话）： https://github.com/WangRongsheng/XrayGLM/blob/main/data/Xray/2577_1.png
cannot identify image file <_io.BytesIO object at 0x7f65dcf1fa10>
```

**Comment by WangRongsheng** [comment]
@AriesChen-UPC 您可以尝试一下用本地路径的图片，URL我们的测试不多。

**Comment by AriesChen-UPC** [comment]
好的，谢谢~

PS: 读取存储于Google Drive中的图像文件也有同样的问题

**Comment by WangRongsheng** [comment]
> 好的，谢谢~
> 
> PS: 读取存储于Google Drive中的图像文件也有同样的问题

晚点会检查，谢谢提醒。
