### ISSUE TITLE
这文件是不是有点不对劲

### ISSUE THREAD

**Issue by Xjmengnieer** [WangRongsheng/XrayGLM#34]
![image](https://github.com/WangRongsheng/XrayGLM/assets/88227513/281c8310-4f69-43cd-91ae-62d4cbae0c82)

如图，这个json文件下根本没有图片的路径呀？

命令仅仅把batch改成了1，把use_lora改成了use_qlora:
![image](https://github.com/WangRongsheng/XrayGLM/assets/88227513/3edf32e0-d045-422d-bd15-e92a61a398f6)

**Comment by Xue-Yw** [comment]
这个文件的标签和代码里是不太对，需要稍微改一下代码，我记得之前有人讨论过这个问题，可以看一下

**Comment by shituo123456** [comment]
> ![image](https://user-images.githubusercontent.com/88227513/246309188-281c8310-4f69-43cd-91ae-62d4cbae0c82.png)
> 
> 如图，这个json文件下根本没有图片的路径呀？
> 
> 命令仅仅把batch改成了1，把use_lora改成了use_qlora: ![image](https://user-images.githubusercontent.com/88227513/246309488-3edf32e0-d045-422d-bd15-e92a61a398f6.png)

您好，这个问题怎么解决呢
