### ISSUE TITLE
为什么我用--qlora训练以后的权重，不能在cli_demo.py中正常加载？

### ISSUE THREAD

**Issue by Xjmengnieer** [WangRongsheng/XrayGLM#37]
![image](https://github.com/WangRongsheng/XrayGLM/assets/88227513/416f3389-c1bf-4c9f-a6de-592e791dfd26)
显示是输入数据尺寸不对，我打印了一下这里的self.wigth.data,其shape为：
![image](https://github.com/WangRongsheng/XrayGLM/assets/88227513/dd1300c5-52d8-470c-95f4-68c3b1ab66c9)
而后，我再打印了一下这里加载的权重：state_dict[prefix+'weight']，其shape为：
![image](https://github.com/WangRongsheng/XrayGLM/assets/88227513/64ef2c73-2103-42f4-9fcd-53fefb3f503b)
这个值恰好是上面self.wigth.data的shape的乘积的一半，而且上面self.wigth.data是float16， 而state_dict[prefix+'weight']是uint8，
能给一点意见吗？感谢

**Comment by Bo2Rim** [comment]
遇到了同样的问题。请问这个问题有解决吗？ @Xjmengnieer
