### ISSUE TITLE
「求解答」data/json 中的训练格式都是 unicode 编码过的内容，这是为什么？

### ISSUE THREAD

**Issue by ONLY-yours** [WangRongsheng/XrayGLM#41]
data下的json数据 prompt 和 label 都是 unicode 编码过的内容。
visual 官方的数据格式应该是支持中文的，转过码的原因是什么？节省训练时候的压力？

![image](https://github.com/WangRongsheng/XrayGLM/assets/52664827/9695f196-fb41-42a7-b84e-bf42da8bc262)

**Comment by WangRongsheng** [comment]
无特殊原因，使用unicode 或utf-8编码都是可以。
