### ISSUE TITLE
微调真的学会了嘛？

### ISSUE THREAD

**Issue by PangziZhang523** [WangRongsheng/XrayGLM#48]
XrayGLM真的学会诊断X片还是只是学会了这种说话的方式，示例里都是判断正常的例子，是否他只学会了说“心脏正常，无明显异常”这类的话，并没有真的学会在X片中的细粒度的诊断？
请解答一下,感谢

**Comment by Suqingyong** [comment]
借楼，请问XRAYGLM现在仅支持X光影响报告生成吗？ 贵团队是否在这个基础上做ct、mri、超声等其他类型医学影像的报告生成？ 近期会有此类预训练好的模型release吗？ 不知道使用此套代码来在ct、mri、超声等数据上进行finetune是否可行？谢谢您。

**Comment by WangRongsheng** [comment]
> 

数据存在显性的不均衡，我们建议在大数据量上进行预训练并且利用本文提供的数据再进行微调，相关实验我们正在做。

**Comment by WangRongsheng** [comment]
> 借楼，请问XRAYGLM现在仅支持X光影响报告生成吗？ 贵团队是否在这个基础上做ct、mri、超声等其他类型医学影像的报告生成？ 近期会有此类预训练好的模型release吗？ 不知道使用此套代码来在ct、mri、超声等数据上进行finetune是否可行？谢谢您。

这可能是未来的一部分工作。

**Comment by Suqingyong** [comment]
> 



> > 借楼，请问XRAYGLM现在仅支持X光影响报告生成吗？ 贵团队是否在这个基础上做ct、mri、超声等其他类型医学影像的报告生成？ 近期会有此类预训练好的模型release吗？ 不知道使用此套代码来在ct、mri、超声等数据上进行finetune是否可行？谢谢您。
> 
> 这可能是未来的一部分工作。

感谢您的回复，我现在在使用您预训练模型，请问XRAYGLM现阶段能否处理肺部CT（例如 肺结节） 这种映像，（好像X光和CT有共性），贵团队有做这方面类似的测试吗？

**Comment by zousss** [comment]
> XrayGLM真的学会诊断X片还是只是学会了这种说话的方式，示例里都是判断正常的例子，是否他只学会了说“心脏正常，无明显异常”这类的话，并没有真的学会在X片中的细粒度的诊断？ 请解答一下,感谢

是的，如果识别不出来异常病例，那怎么证明微调学习到了图片中的内容？
