### ISSUE TITLE
检查发现是https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 对应的visualglm-6b.zip缺失了，

### ISSUE THREAD

**Issue by sujaly** [WangRongsheng/XrayGLM#51]
请楼主提供新的文件下载地址，感谢

**Comment by shituo123456** [comment]
+1

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sujaly** [comment]
已找到解决方案，参考https://github.com/THUDM
  [VisualGLM-6B](https://github.com/THUDM/VisualGLM-6B)中的模型加载部分，将链接替换成MODEL_URLS['visualglm-6b'] = 'r2://visualglm-6b.zip'，

然后更新   sat到最新版
pip install --upgrade SwissArmyTransformer
即可解决上述问题

**Comment by shituo123456** [comment]
> 'r2://visualglm-6b.zip'

非常感谢，已解决

**Comment by shituo123456** [comment]
> 已找到解决方案，参考https://github.com/THUDM [VisualGLM-6B](https://github.com/THUDM/VisualGLM-6B)中的模型加载部分，将链接替换成MODEL_URLS['visualglm-6b'] = 'r2://visualglm-6b.zip'，
> 
> 然后更新 sat到最新版 pip install --upgrade SwissArmyTransformer 即可解决上述问题

非常感谢，已解决。 
想咨询下2080Ti的8卡服务器能微调XrayGLM吗

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wuyanlin-wyl** [comment]
> > 已找到解决方案，参考https://github.com/THUDM [VisualGLM-6B](https://github.com/THUDM/VisualGLM-6B)中的模型加载部分，将链接替换成MODEL_URLS['visualglm-6b'] = 'r2://visualglm-6b.zip'，
> > 然后更新 sat到最新版 pip install --upgrade SwissArmyTransformer 即可解决上述问题
> 
> 非常感谢，已解决。 想咨询下2080Ti的8卡服务器能微调XrayGLM吗

请问这个问题可以更详细的说一下吗

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
