### ISSUE TITLE
CLI推理时报错，缺少checkpoints/checkpoints-XrayGLM-3000/model_config.json文件

### ISSUE THREAD

**Issue by Luchen-0420** [WangRongsheng/XrayGLM#61]
错误发生在 arguments.py 文件的第 446 行，尝试打开位于 'checkpoints/checkpoints-XrayGLM-3000/model_config.json' 路径的文件时出错。这个文件是要去哪里下载吗

**Comment by WangRongsheng** [comment]
model_config.json在：https://huggingface.co/wangrongsheng/XrayGLM-3000/tree/main
